(() => {
  'use strict';
  const synth = window.speechSynthesis;
  const $ = (id) => document.getElementById(id);
  const PRESETS = {
    quick:{label:'3-minute scan',button:'3 min scan',stories:3,filings:1,detail:180,context:100},
    standard:{label:'5-minute brief',button:'5 min brief',stories:5,filings:2,detail:300,context:170},
    deep:{label:'10-minute deep dive',button:'10 min deep dive',stories:8,filings:3,detail:480,context:260}
  };
  let mode='standard', segments=[], stopped=true, initialized=false;

  const clean=(v)=>String(v||'').replace(/\s+/g,' ').trim();
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const trim=(v,n)=>{const t=clean(v);if(t.length<=n)return t;const c=t.slice(0,n);const b=Math.max(c.lastIndexOf('. '),c.lastIndexOf(' '));return `${c.slice(0,b>n*.6?b:n).trim()}…`;};
  const safe=(v)=>{try{const u=new URL(String(v||''));return u.protocol==='https:'?u.href:'';}catch{return '';}};
  const impactRank=(text)=>/high/i.test(text)?3:/medium/i.test(text)?2:1;

  function ensureUi(){
    const panel=document.querySelector('.briefing-panel'), controls=panel?.querySelector('.briefing-controls');
    if(!panel||!controls)return false;
    if(!document.querySelector('link[data-research-radio-style]')){const l=document.createElement('link');l.rel='stylesheet';l.href='./research-radio.css';l.dataset.researchRadioStyle='1';document.head.appendChild(l);}
    panel.querySelector('.briefing-heading .eyebrow').textContent='Research Radio';
    $('briefingTitle').textContent='Listen to what matters';
    const kicker=panel.querySelector('.briefing-kicker');
    if(kicker)kicker.textContent='Choose a listening format. Research Radio prioritizes high-impact and directional evidence, preserves source links, and speaks only research already loaded in this browser.';
    if(!$('radioFormats')){
      const el=document.createElement('div');el.id='radioFormats';el.className='radio-formats';el.innerHTML=`<div class="radio-format-copy"><span class="radio-label">Listening format</span><strong id="radioFormatTitle">5-minute brief</strong><small id="radioEstimate">Target format; actual length varies with available evidence and playback speed.</small></div><div class="radio-format-buttons" role="group" aria-label="Research Radio listening format"><button type="button" data-radio-mode="quick">3 min<span>Quick scan</span></button><button type="button" data-radio-mode="standard" class="active">5 min<span>Research brief</span></button><button type="button" data-radio-mode="deep">10 min<span>Deep dive</span></button><button type="button" data-radio-mode="changes" class="radio-plus" disabled>Changes only<span>Plus</span></button></div><button id="radioWatchlistJump" class="radio-watchlist-jump" type="button" hidden>Whole-watchlist radio →</button>`;controls.before(el);
    }
    return true;
  }

  function cardMeta(card){return Array.from(card.querySelectorAll('.badge')).map((n)=>clean(n.textContent));}
  function stories(){return Array.from(document.querySelectorAll('#newsList .feed-card')).map((card,index)=>{const m=cardMeta(card),low=m.map((x)=>x.toLowerCase()),reasons=Array.from(card.querySelectorAll('.reason')).map((n)=>clean(n.textContent));const impact=m.find((x)=>/potential impact/i.test(x))||'Low potential impact';const direction=m.find((x)=>/possible positive|possible negative|neutral \/ mixed/i.test(x))||'Neutral / mixed';return{kind:'story',title:clean(card.querySelector('h3')?.textContent),summary:clean(card.querySelector('p')?.textContent),reasons,impact,direction,url:safe(card.querySelector('a[href]')?.href),rank:impactRank(impact)*10+(low.some((x)=>x.includes('possible positive')||x.includes('possible negative'))?1:0)-index/1000};}).filter((x)=>x.title).sort((a,b)=>b.rank-a.rank);}
  function filings(){return Array.from(document.querySelectorAll('#filingList .feed-card')).map((card,index)=>{const m=cardMeta(card),impact=m.find((x)=>/potential impact/i.test(x))||'Low potential impact';return{kind:'filing',title:clean(card.querySelector('h3')?.textContent),summary:clean(card.querySelector('.reason')?.textContent),impact,direction:'SEC filing',url:safe(card.querySelector('a[href]')?.href),rank:impactRank(impact)*10-index/1000};}).filter((x)=>x.title).sort((a,b)=>b.rank-a.rank);}
  function changes(){return Array.from(document.querySelectorAll('#sinceList .since-item')).map((card,index)=>{const m=Array.from(card.querySelectorAll('.since-item-meta span')).map((n)=>clean(n.textContent));const kind=m.some((x)=>/SEC filing/i.test(x))?'filing':'story',impact=m.find((x)=>/impact/i.test(x))||'low impact',direction=m.find((x)=>/possible positive|possible negative|neutral/i.test(x))||(kind==='filing'?'SEC filing':'Neutral / mixed');return{kind,title:clean(card.querySelector('h3')?.textContent),summary:clean(card.querySelector('p')?.textContent),impact,direction,url:safe(card.querySelector('a[href]')?.href),rank:impactRank(impact)*10+(/positive|negative/i.test(direction)?1:0)-index/1000};}).filter((x)=>x.title).sort((a,b)=>b.rank-a.rank);}

  function regular(){
    const p=PRESETS[mode]||PRESETS.standard,ticker=clean($('tickerName')?.textContent)||'this ticker',company=clean($('companyName')?.textContent)||ticker;
    const selected=[...stories().slice(0,p.stories),...filings().slice(0,p.filings)];if(!selected.length)return[];
    const out=[{kind:'intro',title:`${ticker} ${p.label}`,text:`Welcome to ShareCapsule Research Radio for ${company}, ticker ${ticker}. The latest displayed price is ${clean($('lastPrice')?.textContent)||'unavailable'}, with ${clean($('dayChange')?.textContent)||'change unavailable'}. Recent coverage is labeled ${clean($('toneLabel')?.textContent)||'mixed or neutral'}, with a tone index of ${clean($('toneScore')?.textContent)||'0'}. This ${p.label} prioritizes the strongest currently displayed evidence.`,url:''}];
    selected.forEach((item,index)=>{if(item.kind==='story'){const context=item.reasons.map((r)=>r.replace(/^Direction context:\s*/i,'').replace(/^Why flagged:\s*/i,'')).filter(Boolean).join(' ');out.push({...item,text:`Story ${index+1}. ${item.title}. This is labeled ${item.direction.toLowerCase()} and ${item.impact.toLowerCase()}. ${trim(item.summary||context,p.detail)}${item.summary&&context?` Why it may matter: ${trim(context,p.context)}`:''}`});}else out.push({...item,text:`SEC filing. ${item.title}. This is a primary-source filing labeled ${item.impact.toLowerCase()} for research prioritization. ${trim(item.summary,p.context)} Review the filing itself before drawing a conclusion.`});});
    out.push({kind:'closing',title:'Research Radio complete',text:`That concludes the ${p.label} for ${ticker}. Direction and impact labels organize research; they do not predict price movement or recommend a trade. Verify material information at the original source.`,url:''});return out;
  }
  function changed(){const ticker=clean($('tickerName')?.textContent)||'this ticker',items=changes().slice(0,8);if(!items.length)return[];const s=items.filter((x)=>x.kind==='story').length,f=items.filter((x)=>x.kind==='filing').length;return[{kind:'intro',title:`${ticker} changes-only catch-up`,text:`Here is your changes-only Research Radio catch-up for ${ticker}. Since the previous encrypted checkpoint on this device, ${s} newly surfaced ${s===1?'story':'stories'} and ${f} new SEC ${f===1?'filing':'filings'} are shown.`,url:''},...items.map((x,i)=>({...x,text:`Change ${i+1}. ${x.title}. ${x.kind==='filing'?'This is a newly surfaced SEC filing.':`This item is labeled ${x.direction.toLowerCase()} and ${x.impact.toLowerCase()}.`} ${trim(x.summary,330)}`})),{kind:'closing',title:'Changes catch-up complete',text:`You are caught up on the newly surfaced evidence currently shown for ${ticker}. Research memory is a prioritization aid, not a price forecast or trade recommendation.`,url:''}];}
  const build=()=>mode==='changes'?changed():regular();
  function runtime(items){const words=items.reduce((n,x)=>n+clean(x.text).split(/\s+/).filter(Boolean).length,0),rate=Math.max(.5,Number($('briefingRate')?.value||1)),min=words/(145*rate);if(!words)return'No playable evidence is available for this format yet.';if(min<1)return`About ${Math.max(20,Math.round(min*60))} sec of current material at ${rate}×.`;return`About ${min.toFixed(min<3?1:0)} min of current material at ${rate}×. Target formats expand only when enough sourced evidence is available.`;}
  function updateEstimate(items){if($('radioEstimate'))$('radioEstimate').textContent=runtime(items||build());}
  function render(){const list=$('briefingTranscript');if(!list)return;list.innerHTML=`<div class="radio-transcript-summary"><strong>${esc(mode==='changes'?'Changes-only catch-up':PRESETS[mode].label)}</strong><span>${esc(runtime(segments))}</span></div>`+segments.map((x,i)=>`<article class="briefing-item radio-item" data-briefing-index="${i}">${['story','filing'].includes(x.kind)?`<div class="briefing-meta"><span>${esc(x.direction||x.kind)}</span><span>${esc(x.impact||'')}</span></div>`:''}<h3>${esc(x.title)}</h3><p>${esc(x.text)}</p>${x.url?`<a href="${esc(x.url)}" target="_blank" rel="noopener noreferrer">Open original source ↗</a>`:''}</article>`).join('');}
  const status=(m)=>{if($('briefingStatus'))$('briefingStatus').textContent=m;};
  function active(i){document.querySelectorAll('[data-briefing-index]').forEach((n)=>n.classList.toggle('active',Number(n.dataset.briefingIndex)===i));if($('briefingProgress'))$('briefingProgress').textContent=segments.length&&i>=0?`${i+1} / ${segments.length}`:`0 / ${segments.length}`;document.querySelector(`[data-briefing-index="${i}"]`)?.scrollIntoView({block:'nearest',behavior:'smooth'});}
  function voice(){const uri=$('briefingVoice')?.value,v=synth?.getVoices?.()||[];return(uri?v.find((x)=>x.voiceURI===uri):null)||v.find((x)=>/^en(-|_)/i.test(x.lang)&&x.localService&&x.default)||v.find((x)=>/^en(-|_)/i.test(x.lang)&&x.localService)||null;}
  function speak(i){if(!synth||stopped||i>=segments.length){if(i>=segments.length){stopped=true;active(-1);status('Research Radio complete. Use the transcript links to read any source in full.');if($('briefingPause'))$('briefingPause').disabled=true;if($('briefingStop'))$('briefingStop').disabled=true;}return;}const x=segments[i],u=new SpeechSynthesisUtterance(x.text),v=voice();if(v)u.voice=v;u.lang=v?.lang||'en-US';u.rate=Number($('briefingRate')?.value||1);u.onstart=()=>{active(i);status(['story','filing'].includes(x.kind)?`Playing research item ${i} of ${Math.max(1,segments.length-2)}.`:x.title);};u.onend=()=>{if(!stopped)speak(i+1);};u.onerror=(e)=>{if(['canceled','interrupted'].includes(e.error))return;stopped=true;status(`Research Radio could not continue: ${e.error||'speech synthesis error'}. The transcript remains available.`);};synth.speak(u);}
  function play(e){e?.preventDefault();e?.stopImmediatePropagation();segments=build();render();updateEstimate(segments);if(!segments.length){stopped=true;return status(mode==='changes'?'No newly surfaced evidence is available in “Since I last checked” yet. Choose another format or refresh after a later update.':'Load ticker news or SEC filings first, then start Research Radio.');}if(!synth||typeof SpeechSynthesisUtterance==='undefined'){stopped=true;return status('Speech synthesis is unavailable in this browser. The Research Radio transcript is still available.');}synth.cancel();stopped=false;if($('briefingPause')){$('briefingPause').disabled=false;$('briefingPause').textContent='Pause';}if($('briefingStop'))$('briefingStop').disabled=false;speak(0);}
  function pause(e){e?.preventDefault();e?.stopImmediatePropagation();if(!synth||stopped)return;if(synth.paused){synth.resume();$('briefingPause').textContent='Pause';status('Research Radio resumed.');}else{synth.pause();$('briefingPause').textContent='Resume';status('Research Radio paused.');}}
  function stop(e){e?.preventDefault();e?.stopImmediatePropagation();stopped=true;synth?.cancel();active(-1);if($('briefingPause')){$('briefingPause').textContent='Pause';$('briefingPause').disabled=true;}if($('briefingStop'))$('briefingStop').disabled=true;status('Research Radio stopped. The transcript remains available.');}

  function availability(){if(!ensureUi())return;const c=changes(),btn=document.querySelector('[data-radio-mode="changes"]');if(btn){btn.disabled=!c.length;btn.title=c.length?`${c.length} newly surfaced item${c.length===1?'':'s'} ready to hear`:'Available when Plus research memory detects newly surfaced evidence';}const jump=$('radioWatchlistJump'),whole=document.querySelector('.watchlist-briefing-panel');if(jump)jump.hidden=!whole;if(mode==='changes'&&!c.length)select('standard');else{const playBtn=$('briefingPlay');if(playBtn)playBtn.disabled=mode==='changes'?!c.length:stories().length+filings().length===0;}}
  function select(next){if(next==='changes'&&!changes().length)return;if(next!=='changes'&&!PRESETS[next])return;mode=next;document.querySelectorAll('[data-radio-mode]').forEach((b)=>b.classList.toggle('active',b.dataset.radioMode===mode));if($('radioFormatTitle'))$('radioFormatTitle').textContent=mode==='changes'?'Changes-only catch-up':PRESETS[mode].label;if($('briefingPlay'))$('briefingPlay').textContent=mode==='changes'?'Play latest changes':`Play ${PRESETS[mode].button}`;updateEstimate();availability();if(stopped)status(mode==='changes'?'Changes-only mode speaks only the newly surfaced evidence currently shown by Plus research memory.':`${PRESETS[mode].label} selected. Research Radio will prioritize the strongest currently displayed evidence.`);}
  function observe(id){const n=$(id);if(n)new MutationObserver(()=>{availability();if(stopped)updateEstimate();}).observe(n,{childList:true,subtree:true,attributes:true,attributeFilter:['hidden']});}
  function bind(){if(initialized||!ensureUi())return;initialized=true;document.querySelectorAll('[data-radio-mode]').forEach((b)=>b.addEventListener('click',()=>select(b.dataset.radioMode)));$('briefingPlay')?.addEventListener('click',play,true);$('briefingPause')?.addEventListener('click',pause,true);$('briefingStop')?.addEventListener('click',stop,true);$('briefingRate')?.addEventListener('change',()=>updateEstimate());$('radioWatchlistJump')?.addEventListener('click',()=>document.querySelector('.watchlist-briefing-panel')?.scrollIntoView({behavior:'smooth',block:'start'}));observe('newsList');observe('filingList');observe('sinceLastCheckedPanel');window.addEventListener('beforeunload',()=>synth?.cancel());availability();select('standard');}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
